// src/constants/masjidsData.js

export const MASJIDS_DATA = {
  'masjid-1': {
    id: 'masjid-1',
    name: 'Masjid 1',
    isMosque: true,
    slug: 'masjid-1',
    logoUrl: '/logos/Masjid Logos/Masjid 1/logo.png',
    adminEnrolmentEmail: 'eirfathchoudhury@gmail.com',
    resendApiKeyEnv: 'RESEND_API_KEY_MASJID_1',
    prayerTimesCsvUrl:
      'https://docs.google.com/spreadsheets/d/e/2PACX-1vTrTt62Km6insJb8EymYx4JDizx98rohedugT1lfs8d2ZoG-ponnG9NeKr9iIebF4K_BwU-zCDrU41g/pub?gid=622300626&single=true&output=csv',
    classesCsvUrl:
      'https://docs.google.com/spreadsheets/d/e/2PACX-1vRcdSknt0Iytd_IQP9QBVMUPRW0L5LfIngKKcu0SMd4JEeICWvhpE6YSeY6nnKCiY2ez0QoApFbEtHW/pub?gid=1229947143&single=true&output=csv',
    contact: {
      address: '123 High Street, Gillingham, ME7 1BQ',
      phone: '+44 1634 123456',
      email: 'info@masjid1.com',
      charityNumber: '1234567',
    },
    donation: {
      accountName: 'Masjid 1 Trust',
      bankName: 'Barclays Bank',
      sortCode: '20-00-00',
      accountNumber: '12345678',
      onlineDonationUrl: 'https://donate.masjid1.com',
    },
    services: [
      {
        id: 1,
        icon: 'Moon',
        title: 'Daily Congregational Prayers',
        price: 'Free / Community Service',
        priceNote: 'Open to all',
        description: "Accommodating hundreds of worshippers for the five compulsory daily prayers, alongside weekly Friday Jumu'ah sermons led by experienced scholars.",
      },
      {
        id: 2,
        icon: 'BookOpen',
        title: 'Islamic & Quranic Academy',
        price: '£35 / month',
        priceNote: 'Per student (Subsidies available)',
        description: 'Structured weekend school modules, evening Tajweed programs, and specialized Hifz circles designed for students of all age groups.',
      },
      {
        id: 3,
        icon: 'HeartHandshake',
        title: 'Nikah & Marriage Services',
        price: '£150',
        priceNote: 'Includes official certificate & registry',
        description: 'Conducting official Islamic marriage ceremonies complete with counseling sessions to support families building strong, faith-centered foundations.',
      },
      {
        id: 4,
        icon: 'Users',
        title: 'Family Support & Counseling',
        price: 'Free',
        priceNote: 'Confidential appointment required',
        description: 'Confidential, compassionate guidance sessions addressing personal, spiritual, or familial challenges with trusted scholars and advisors.',
      },
      {
        id: 5,
        icon: 'ShieldCheck',
        title: 'Funeral & Janazah Coordination',
        price: 'Cost of Burial / At Cost',
        priceNote: 'Complete coordination support',
        description: 'Providing complete, dignity-honoring funeral arrangements according to sacred traditions, supporting families through times of loss.',
      },
    ],
    facilities: [
      {
        id: 1,
        icon: 'Car',
        title: 'Main Car Park',
        category: 'Amenities',
        details: [
          { label: 'Total Spaces', value: '120 Bays' },
          { label: 'EV Charging', value: '4 Points' },
          { label: 'Accessible Bays', value: '6 Spaces' },
        ],
        status: 'Open',
        description: 'Secure, well-lit on-site parking enclosure with dedicated wide access points for families and elderly visitors.',
      },
      {
        id: 2,
        icon: 'Landmark',
        title: 'Main Prayer Hall (Men)',
        category: 'Prayer Spaces',
        details: [
          { label: 'Capacity', value: '800 Worshippers' },
          { label: 'Audio Loop', value: 'Active / Installed' },
          { label: 'Floor Level', value: 'Ground Level' },
        ],
        status: 'Open',
        description: 'The primary expansive congregational prayer hall featuring high vaulted ceilings, optimized acoustic dispersion, and full climate control.',
      },
      {
        id: 3,
        icon: 'Users',
        title: 'Sisters Prayer Balcony',
        category: 'Prayer Spaces',
        details: [
          { label: 'Capacity', value: '350 Worshippers' },
          { label: 'Privacy Screen', value: 'One-Way Tinted Glass' },
          { label: 'Lift Access', value: 'Available' },
        ],
        status: 'Open',
        description: 'A beautifully elevated, serene prayer space designed exclusively for women, offering an unobstructed acoustic view of the main hall.',
      },
      {
        id: 4,
        icon: 'Droplets',
        title: "Men's Wudhu Area",
        category: 'Amenities',
        details: [
          { label: 'Stations', value: '25 Faucets' },
          { label: 'Foot Baths', value: '4 Available' },
          { label: 'Seating', value: 'Granite Stools' },
        ],
        status: 'Open',
        description: 'High-capacity ritual purification facility equipped with automated anti-scald mixing valves and continuous slip-resistant underfoot drainage tracks.',
      },
      {
        id: 5,
        icon: 'Sparkles',
        title: "Women's Wudhu Suite",
        category: 'Amenities',
        details: [
          { label: 'Stations', value: '18 Faucets' },
          { label: 'Private Cubicles', value: '4 Fully Enclosed' },
          { label: 'Vanity Mirror Ring', value: 'Installed' },
        ],
        status: 'Open',
        description: 'A completely private, secure, and modern purification suite offering vanity areas, changing spaces, and dedicated baby-changing facilities.',
      },
    ],
    gallery: [
      { id: 1, src: '/images/Masjid/Masjid 1/gallery/interior-1.jpg', alt: 'Main Prayer Hall Vaulted Archways' },
      { id: 2, src: '/images/Masjid/Masjid 1/gallery/interior-2.jpg', alt: 'Intricate Calligraphy Mihrab Niche' },
      { id: 3, src: '/images/Masjid/Masjid 1/gallery/interior-3.jpg', alt: 'Central Chandelier & Dome Framework' },
      { id: 4, src: '/images/Masjid/Masjid 1/gallery/interior-4.jpg', alt: 'Community Library & Reading Annex' },
      { id: 5, src: '/images/Masjid/Masjid 1/gallery/interior-5.jpg', alt: 'Serene Courtyard Ablution Fountain Area' },
    ],
    team: [
      {
        id: 1,
        image: '/images/Masjid/Masjid 1/team/imam.jpg',
        name: 'Sheikh Dr. Mohamed Al-Azhari',
        role: 'Head Imam & Religious Director',
        description: 'Serving as our primary spiritual guide for over a decade, Sheikh Mohamed coordinates religious rulings, family integration tracks, and cross-cultural outreach programs.',
        qualifications: [
          'Ph.D. in Islamic Jurisprudence (Al-Azhar University)',
          'Masters in Classical Arabic Literature',
          'Ijazah in the Ten Canonical Quranic Recitations',
        ],
      },
      {
        id: 2,
        image: '/images/Masjid/Masjid 1/team/scholar-sisters.jpg',
        name: 'Ustadha Amina Khan',
        role: 'Director of Sisters Education',
        description: 'Ustadha Amina manages foundational development programs, curriculum design pipelines, and specialized adult spiritual circles.',
        qualifications: [
          'B.A. in Shariah Law (University of Madinah Pathway)',
          'Advanced Diploma in Hadith Sciences',
          'Certified Family & Youth Development Counselor',
        ],
      },
    ],
  },
  'masjid-2': {
    id: 'masjid-2',
    name: 'Masjid 2',
    isMosque: true,
    slug: 'masjid-2',
    logoUrl: '/logos/Masjid Logos/Masjid 2/logo.png',
    adminEnrolmentEmail: 'eirfathchoudhury@gmail.com',
    resendApiKeyEnv: 'RESEND_API_KEY_MASJID_2',
    prayerTimesCsvUrl:
      'https://docs.google.com/spreadsheets/d/e/2PACX-1vQyWFD4HFzZH0IKBUF3ioFUGYuPfAjGZm-v3i5vr3T5zlBXFvya36zEZUwl0QWO-MHjIQwk6nvsgjyo/pub?gid=622300626&single=true&output=csv',
    classesCsvUrl:
      'https://docs.google.com/spreadsheets/d/e/2PACX-1vTCfkdvuOJ65QYnp_7fmGziFOcA8awrRyxQv8SJwCDDn6-Qx4yHyvSrzS87_MPoY2pPFZ7UfvTjkz57/pub?gid=1229947143&single=true&output=csv',
    contact: {
      address: '456 London Road, Gillingham, ME7 2AB',
      phone: '+44 1634 654321',
      email: 'info@masjid2.com',
      charityNumber: '7654321',
    },
    donation: {
      accountName: 'Masjid 2 Trust',
      bankName: 'Lloyds Bank',
      sortCode: '30-00-00',
      accountNumber: '87654321',
      onlineDonationUrl: 'https://donate.masjid2.com',
    },
    services: [
      {
        id: 1,
        icon: 'Moon',
        title: 'Daily Congregational Prayers',
        price: 'Free / Community Service',
        priceNote: 'Open to all',
        description: "Daily prayers and Friday Jumu'ah services.",
      },
      {
        id: 2,
        icon: 'HeartHandshake',
        title: 'Nikah & Marriage Services',
        price: '£120',
        priceNote: 'Includes official certificate',
        description: 'Conducting official Islamic marriage ceremonies and pre-marital advice.',
      },
    ],
    facilities: [
      {
        id: 1,
        icon: 'Car',
        title: 'On-Site Parking',
        category: 'Amenities',
        details: [
          { label: 'Total Spaces', value: '45 Bays' },
          { label: 'Accessible Bays', value: '3 Spaces' },
        ],
        status: 'Open',
        description: 'Dedicated front and rear parking spaces for worshippers and visitors.',
      },
      {
        id: 2,
        icon: 'Landmark',
        title: 'Main Prayer Hall',
        category: 'Prayer Spaces',
        details: [
          { label: 'Capacity', value: '400 Worshippers' },
          { label: 'Climate Control', value: 'Air Conditioned' },
        ],
        status: 'Open',
        description: 'Spacious carpeted prayer hall serving daily prayers and community gatherings.',
      },
      {
        id: 3,
        icon: 'Droplets',
        title: 'Ablution / Wudhu Area',
        category: 'Amenities',
        details: [
          { label: 'Stations', value: '12 Faucets' },
          { label: 'Foot Baths', value: '2 Available' },
        ],
        status: 'Open',
        description: 'Clean ritual washing facilities with anti-slip flooring.',
      },
    ],
    gallery: [
      { id: 1, src: '/images/Masjid/Masjid 2/gallery/interior-1.jpg', alt: 'Prayer Hall View' },
      { id: 2, src: '/images/Masjid/Masjid 2/gallery/interior-2.jpg', alt: 'Mihrab Area' },
      { id: 3, src: '/images/Masjid/Masjid 2/gallery/interior-3.jpg', alt: 'Entrance and Foyer' },
      { id: 4, src: '/images/Masjid/Masjid 2/gallery/interior-4.jpg', alt: 'Classroom Facility' },
      { id: 5, src: '/images/Masjid/Masjid 2/gallery/interior-5.jpg', alt: 'Wudhu Area' },
    ],
    team: [
      {
        id: 1,
        image: '/images/Masjid/Masjid 2/team/imam.jpg',
        name: 'Imam Tariq Mahmood',
        role: 'Resident Imam',
        description: 'Leading daily prayers, providing spiritual guidance, and conducting community study circles.',
        qualifications: [
          'Graduate of Islamic Sciences',
          'Hafiz of the Holy Quran',
          'Certified Marriage Counselor',
        ],
      },
      {
        id: 2,
        image: '/images/Masjid/Masjid 2/team/scholar-sisters.jpg',
        name: 'Ustadha Maryam Ali',
        role: 'Islamic Studies Instructor',
        description: 'Leading Tajweed and Quranic comprehension classes for children and adult sisters.',
        qualifications: [
          'Diploma in Quranic Studies',
          'Ijazah in Hafs an Asim',
        ],
      },
    ],
  },
  'community-hub-1': {
    id: 'community-hub-1',
    name: 'Medway Islamic Community Trust',
    isMosque: false,
    slug: 'medway-community-trust',
    logoUrl: '/logos/KOA Logos/logo.png',
    adminEnrolmentEmail: 'contact@medwaytrust.org',
    resendApiKeyEnv: 'RESEND_API_KEY_COMMUNITY_1',
    contact: {
      address: '78 Canterbury Street, Gillingham, ME7 5YL',
      phone: '+44 1634 889900',
      email: 'info@medwaytrust.org',
      charityNumber: '1198765',
    },
    donation: {
      accountName: 'Medway Islamic Community Trust',
      bankName: 'HSBC UK',
      sortCode: '40-22-00',
      accountNumber: '99887766',
      onlineDonationUrl: 'https://donate.medwaytrust.org',
    },
    services: [
      {
        id: 1,
        icon: 'HeartHandshake',
        title: 'Food Bank & Welfare Aid',
        price: 'Free',
        priceNote: 'Open to all families in need',
        description: 'Weekly distribution of fresh groceries, dry pantry staples, and essential emergency care packages for local households.',
      },
      {
        id: 2,
        icon: 'BookOpen',
        title: 'Youth Mentorship & Tutoring',
        price: 'Free',
        priceNote: 'Registration required',
        description: 'Structured after-school academic support, GCSE prep circles, and career guidance workshops for young members of the community.',
      },
      {
        id: 3,
        icon: 'Users',
        title: 'Senior Citizens Social Hub',
        price: 'Free',
        priceNote: 'Every Wednesday morning',
        description: 'Community gathering space providing tea, health check workshops, gentle mobility exercises, and social connection for elders.',
      },
    ],
    facilities: [
      {
        id: 1,
        icon: 'Building2',
        title: 'Multipurpose Community Hall',
        category: 'Spaces',
        details: [
          { label: 'Capacity', value: '150 People' },
          { label: 'AV System', value: 'Projector & Mic Setup' },
        ],
        status: 'Open',
        description: 'Flexible hall available for community workshops, seminars, youth clubs, and charity events.',
      },
      {
        id: 2,
        icon: 'Coffee',
        title: 'Community Café & Lounge',
        category: 'Amenities',
        details: [
          { label: 'Seating', value: '40 Seats' },
          { label: 'Wi-Fi', value: 'Complimentary High-Speed' },
        ],
        status: 'Open',
        description: 'Warm, welcoming coffee and social lounge offering hot drinks and dedicated quiet study corners.',
      },
    ],
    gallery: [],
    team: [
      {
        id: 1,
        image: '/images/placeholder-avatar.jpg',
        name: 'Brother Zayd Rahman',
        role: 'Trust Coordinator & Community Lead',
        description: 'Managing outreach partnerships, food pantry logistics, and youth empowerment initiatives across the borough.',
        qualifications: [
          'B.Sc. in Social Policy & Administration',
          'Certified Youth Worker (Level 3)',
        ],
      },
    ],
  },
};

export const DEFAULT_MASJID_ID = 'masjid-1';